config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :nutrients
  resources :weights, only: [:new, :create, :show, :destroy]
  resources :products, except: [:show]
  post "add_product", to: "weights#add_product_to_ration"
  delete "remove_product/:id", to: "weights#remove_product_from_ration", as: "remove_product"
end

app/models/nutrient.rb
class Nutrient < ActiveRecord::Base
  validates :name, :cal_per_gram, :percents, presence: { message: "Должно быть заполнено" }
  validates :cal_per_gram, :percents, numericality: { messsage: "Только цифры" }
end

app/models/product.rb
class Product < ActiveRecord::Base
  TYPES = %w(fat protein carbohydrate)

  validates :name, :calories_per_hundred_grams,
            :product_type, presence: { message: "Должно быть заполнено" }
  validates :calories_per_hundred_grams, numericality: { message: "Только цифры" }
  validates :product_type, inclusion: { in: TYPES, message: "Только из списка" }

  has_many :product_rations, dependent: :destroy
  has_many :rations, through: :product_rations

  scope :proteins, -> { where(product_type: "protein") }
  scope :carbohydrates, -> { where(product_type: "carbohydrate") }

  def self.carbs(ration_id)
    joins("INNER JOIN product_rations ON product_rations.product_id = products.id AND products.product_type = 'carbohydrate'")
    .where("product_rations.ration_id = ?", ration_id)
  end

  def self.prots(ration_id)
    joins("INNER JOIN product_rations ON product_rations.product_id = products.id AND products.product_type = 'protein'")
    .where("product_rations.ration_id = ?", ration_id)
  end
end

app/models/product_ration.rb
class ProductRation < ActiveRecord::Base
  belongs_to :product
  belongs_to :ration

  validates :product_id, uniqueness: { scope: :ration_id, message: "Уже добавлен" }
  validates :product_id, :ration_id, presence: { message: "Выберите продукт" }
end

app/models/ration.rb
class Ration < ActiveRecord::Base
  has_many :product_rations, dependent: :destroy
  has_many :products, through: :product_rations

  validates :my_weight, presence: { message: "Должно быть заполнено" },
            uniqueness: { message: "Этот вес уже есть" }

  after_create :calculate_params

  private

  def calculate_params
    total_calories = self.my_weight * 26
    proteins = (total_calories / 100) * Nutrient.find_by_name("Protein").percents
    fat = (total_calories / 100) * Nutrient.find_by_name("Fat").percents
    carbohydrates = (total_calories / 100) * Nutrient.find_by_name("Carbohydrate").percents
    update_attribute(:total_calories, total_calories)
    update_attribute(:proteins, proteins)
    update_attribute(:fat, fat)
    update_attribute(:carbohydrates, carbohydrates)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  private

  def record_not_found
    flash[:alert] = "record not found"
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nutrients = Nutrient.all
    @weights = Ration.all
  end
end

app/controllers/nutrients_controller.rb
class NutrientsController < ApplicationController
  before_action :set_nutrient, only: [:show, :edit, :update, :destroy]

  def index
    @nutrients = Nutrient.all
  end

  def new
    @nutrient = Nutrient.new
  end

  def create
    @nutrient = Nutrient.new(nutrient_params)
    if @nutrient.save
      flash[:notice] = "Сохранено удачно"
      redirect_to nutrients_path
    else
      flash.now[:alert] = "Не сохранено"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @nutrient.update(nutrient_params)
      flash[:notice] = "Значение обновлено"
      redirect_to nutrients_path
    else
      flash.now[:alert] = "Не обновлено"
      render :edit
    end
  end

  def destroy
    @nutrient.destroy
    flash[:notice] = "Значение удалено"
    redirect_to nutrients_path
  end

  private

  def set_nutrient
    @nutrient = Nutrient.find(params[:id])
  end

  def nutrient_params
    params.require(:nutrient).permit(:name, :cal_per_gram, :percents)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all.order("product_type ASC")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Сохранено удачно"
      redirect_to products_path
    else
      flash.now[:alert] = "Не сохранено"
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:notice] = "Значение обновлено"
      redirect_to products_path
    else
      flash.now[:alert] = "Не обновлено"
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = "Значение удалено"
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :calories_per_hundred_grams, :product_type)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :destroy, :remove_product_from_ration]

  def show
    @products_proteins = Product.proteins
    @products_carbohydrates = Product.carbohydrates
    @products_in_list = ProductRation.new
    @carbohydrates = Product.carbs(params[:id])
    @proteins = Product.prots(params[:id])
  end

  def new
    @weight = Ration.new
  end

  def create
    @weight = Ration.new(weight_params)
    if @weight.save
      flash[:notice] = "Сохранено удачно"
      redirect_to root_path
    else
      flash.now[:alert] = "Не сохранено"
      render :new
    end
  end

  def add_product_to_ration
    @products_in_list = ProductRation.new(products_in_list_params)
    if @products_in_list.save
      flash[:notice] = "Продукт доавлен в список"
      redirect_to weight_path(params[:product_ration][:ration_id])
    else
      flash[:alert] = @products_in_list.errors.get(:product_id).join("")
      redirect_to weight_path(params[:product_ration][:ration_id])
    end
  end

  def remove_product_from_ration
    product_in_ration = ProductRation.find_by_product_id_and_ration_id(
      params[:product_id], @weight.id
    )
    product_in_ration.destroy
    flash[:notice] = "Продукт удален из списка"
    redirect_to weight_path
  end

  def destroy
    @weight.destroy
    flash[:notice] = "Значение удалено"
    redirect_to root_path
  end

  private

  def set_weight
    @weight = Ration.find(params[:id])
  end

  def weight_params
    params.require(:ration).permit(:my_weight)
  end

  def products_in_list_params
    params.require(:product_ration).permit(:product_id, :ration_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nutrients_helper.rb
module NutrientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
  def food_per_day(weight, product)
    ((weight.to_f / 4) / product.calories_per_hundred_grams.to_f * 100).to_i
  end

  def food_per_one_time(weight, product)
    (((weight.to_f / 4) / product.calories_per_hundred_grams.to_f * 100).to_i) / 6
  end
end

app/views/home/index.html.haml
%h1 Домашняя страница

.row
  .col-md-12
    %h3 Нутриенты
    - if @nutrients.empty?
      %h4 Еще ничего не добавлено
    - else
      %table.table
        %thead
          %th Название
          %th Калорий в грамме
          %th Процентов в пище
        %tbody
          - @nutrients.each do |n|
            %tr.success
              %td
                = n.name
              %td
                = n.cal_per_gram
                калл на грамм
              %td
                = n.percents
                \%

  .col-md-6
    %h3 Рацион для веса
    - if @weights.empty?
      %h4 Еще ничего не добавлено
    - else
      %table.table.table-hover
        %thead
          %th Вес
          %th Действия
        %tbody
        - @weights.each do |w|
          %tr
            %td
              = w.my_weight
              кг
            %td
              = link_to "Посмотреть рацион", weight_path(w), class: "btn btn-info btn-xs"
              = link_to "X", weight_path(w), method: :delete, data: {confirm: "Точно?"},
                class: "btn btn-danger btn-xs"
  .col-md-6

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CaloriesCalc
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .row
      .col-md-1
      .col-md-10
        %ul.nav.nav-tabs
          %li{role: "presentation", class: "#{params[:controller] == 'home' ? 'active' : ''}"}
            = link_to "Главная", root_path
          %li{role: "presentation", class: "#{params[:controller] == 'products' ? 'active' : ''}"}
            = link_to "Продукты", products_path
          %li{role: "presentation", class: "#{params[:controller] == 'nutrients' ? 'active' : ''}"}
            = link_to "Нутриенты", nutrients_path
          %li{role: "presentation", class: "#{params[:controller] == 'weights' ? 'active' : ''}"}
            = link_to "Рацион/Добавить вес", new_weight_path

        - flash.each do |key, message|
          %div{class: "alert alert-#{ key } alert-dismissible", role: "alert"}
            %button{type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close"}
              %span{"aria-hidden": "true"}
                &times;
            = message
        = yield
      .col-md-1

app/views/nutrients/_form.html.haml
.col-md-1
.col-md-8
  = simple_form_for(@nutrient) do |f|
    = f.label :name, "Название"
    = f.input :name, label: false
    = f.label :cal_per_gram, "Калорий в грамме"
    = f.input :cal_per_gram, label: false
    = f.label :percents, "Процентов от рациона"
    = f.input :percents, label: false
    %br
    = f.submit "#{ @nutrient.persisted? ? 'Редактировать' : 'Добавить'}", class: "btn btn-primary"
.col-md-1

app/views/nutrients/edit.html.haml
%h1 Редактировать нутриент

= render partial: "form"

app/views/nutrients/index.html.haml
%h1 Нутриенты
= link_to "Добавить новый", new_nutrient_path, class: "btn btn-info"

.row
  .col-md-12
  - if @nutrients.empty?
    %h4 Еще ничего не добавлено
  - else
    %table.table
      %thead
        %th Название
        %th Калорий в грамме
        %th Процентов в пище
        %th Действия
      %tbody
        - @nutrients.each do |n|
          %tr
            %td
              = n.name
            %td
              = n.cal_per_gram
              калл на грамм
            %td
              = n.percents
              \%
            %td
              = link_to "Редактировать", edit_nutrient_path(n), class: "btn btn-warning btn-xs"
              = link_to "X", nutrient_path(n), method: :delete, data: {confirm: "Точно?"},
                class: "btn btn-danger btn-xs"

app/views/nutrients/new.html.haml
%h1 Добавить нутриент

= render partial: "form"

app/views/products/_form.html.haml
.col-md-1
.col-md-8
  = simple_form_for(@product) do |f|
    = f.label :name, "Название"
    = f.input :name, label: false
    = f.label :calories_per_hundred_grams, "Калорий в грамме"
    = f.input :calories_per_hundred_grams, label: false
    = f.label :product_type, "Тип нутриента"
    = f.input :product_type, collection: Product::TYPES, label: false
    %br
    = f.submit "#{ @product.persisted? ? 'Редактировать' : 'Добавить'}", class: "btn btn-primary"
.col-md-3

app/views/products/edit.html.haml
%h3 Редактировать продукт

= render partial: "form"

app/views/products/index.html.haml
%h1 Продукты
= link_to "Добавить новый", new_product_path, class: "btn btn-info"

.row
  .col-md-12
    -if @products.empty?
      %h4 Еще ничего не добавлено
    - else
      %table.table
        %thead
          %th Название
          %th Калорий на 100 грамм
          %th Тип нутриента
          %th Действия
        %tbody
          - @products.each do |p|
            %tr
              %td
                = p.name
              %td
                = p.calories_per_hundred_grams
              %td
                = p.product_type
              %td
                = link_to "Редактировать", edit_product_path(p), class: "btn btn-warning btn-xs"
                = link_to "X", product_path(p), method: :delete, data: {confirm: "Точно?"},
                  class: "btn btn-danger btn-xs"

app/views/products/new.html.haml
%h3 Добавить продукт

= render partial: "form"

app/views/weights/new.html.haml
%h3 Добавить вес

.col-md-1
.col-md-8
  = simple_form_for(@weight, url: weights_path) do |f|
    = f.label :my_weight, "Ввести вес"
    = f.input :my_weight, label: false
    = f.submit "Добавить", class: "btn btn-primary"
.col-md-1

app/views/weights/show.html.haml
%h3.text-success
  Вес тела:
  = @weight.my_weight.to_i
  кг
%h4.text-primary
  Всего каллорий за день:
  = @weight.total_calories
  ккал

.row
  .col-md-12
    .row
      .col-md-6
        %h3.text-info Нутриентов за день:
        %ul.list-group
          %li.list-group-item
            Белки -
            = @weight.proteins / 4
            грамм
          %li.list-group-item
            Жиры -
            = @weight.fat / 9
            грамм
          %li.list-group-item
            Углеводы -
            = @weight.carbohydrates / 4
            грамм
      .col-md-6
        - unless @products_proteins.empty? && @products_carbohydrates.empty?
          %h3.text-info Добавить продукты в рацион:
        - unless @products_proteins.empty?
          = simple_form_for(@products_in_list, url: add_product_path) do |f|
            .col-md-11
              = f.input :product_id, collection: @products_proteins, label: false, prompt: "Белки"
              = f.hidden_field :ration_id, value: @weight.id
            .col-md-1
              = f.submit "+", class: "btn btn-primary"
        - unless @products_carbohydrates.empty?
          = simple_form_for(@products_in_list, url: add_product_path) do |f|
            .col-md-11
              = f.input :product_id, collection: @products_carbohydrates, label: false,
                prompt: "Углеводы"
              = f.hidden_field :ration_id, value: @weight.id
            .col-md-1
              = f.submit "+", class: "btn btn-primary"

.row
  .col-md-12
    %h3.text-info Еды за день:
    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-warning Углеводы
      - if @carbohydrates.empty?
        %li.list-group-item Еще ничего не добавлено
      - else
        - @carbohydrates.each do |pr|
          %li.list-group-item
            = pr.name
            \:
            = food_per_day(@weight.carbohydrates, pr)
            грамм
            = link_to "X", remove_product_path(product_id: pr.id),
              method: :delete, data: {confirm: "Точно?"},
              class: "btn btn-danger btn-xs"
          - unless pr.id == @carbohydrates.last.id
            %li.list-group-item
              или
    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-warning Белки
      - if @proteins.empty?
        %li.list-group-item Еще ничего не добавлено
      - else
        - @proteins.each do |pr|
          %li.list-group-item
            = pr.name
            \:
            = food_per_day(@weight.proteins, pr)
            грамм
            = link_to "X", remove_product_path(product_id: pr.id),
              method: :delete, data: {confirm: "Точно?"},
              class: "btn btn-danger btn-xs"
          - unless pr.id == @proteins.last.id
            %li.list-group-item
              или

    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-warning Жиры
      %li.list-group-item
        включены в расчет
.row
  .col-md-12
    %h3.text-info Еды за прием пищи:

    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-success Углеводы
      - if @carbohydrates.empty?
        %li.list-group-item Еще ничего не добавлено
      - else
        - @carbohydrates.each do |pr|
          %li.list-group-item
            = pr.name
            \:
            = food_per_one_time(@weight.carbohydrates, pr)
            грамм
          - unless pr.id == @carbohydrates.last.id
            %li.list-group-item
              или

    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-success Белки
      - if @proteins.empty?
        %li.list-group-item Еще ничего не добавлено
      - else
        - @proteins.each do |pr|
          %li.list-group-item
            = pr.name
            \:
            = food_per_one_time(@weight.proteins, pr)
            грамм
          - unless pr.id == @proteins.last.id
            %li.list-group-item
              или

    %ul.list-group.col-md-4
      %li.list-group-item
        %h4.text-success Жиры
      %li.list-group-item
        включены в расчет